version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16.13

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /*.*.*/